name: app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.2
  visibility_detector: ^0.4.0+2
  # riverpod: ^2.6.1
  url_launcher: ^6.1.10
  flutter_riverpod: ^2.6.1
  recase: ^4.1.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.2.3
  image_size_getter: ^2.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/items/
    - assets/icons/
